- name: Install fastfetch on AlmaLinux
  become: true
  ansible.builtin.dnf:
    name: fastfetch
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: Install fastfetch on MacOS
  community.general.homebrew:
    name: fastfetch
    state: present
  when: ansible_distribution == "MacOSX"

- name: Create fastfetch config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fastfetch"
    state: directory
    mode: 0755

- name: Configure fastfetch
  ansible.builtin.copy:
    src: ../files/fastfetch.jsonc
    dest: "{{ ansible_env.HOME }}/.config/fastfetch/config.jsonc"
    mode: 0644
