---
- name: Install Wezterm
  community.general.homebrew:
    name: wezterm
    state: present

- name: Copy Wezterm configuration file
  ansible.builtin.template:
    src: ../files/wezterm_lua.j2
    dest: "{{ ansible_env.HOME }}/.wezterm.lua"
